project_id = "irbyoeorqdqokeyrtwgi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovableproject.com"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[edge_runtime]
enabled = true
port = 54325
inspector_port = 54321

[functions.get-weather]
verify_jwt = false

[functions.search-youtube]
verify_jwt = false

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"