// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irbyoeorqdqokeyrtwgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyYnlvZW9ycWRxb2tleXJ0d2dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzAzMjIsImV4cCI6MjA3MzQ0NjMyMn0.O8yalKL8uAbEQg64lszJrsFBoD9k_WMaxNASbMGWBT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});